### ISSUE TITLE
Please update InvoiceNinja_v5 to 5.10

### ISSUE THREAD

**Issue by SpitFireRSA** [kiwimato/unraid-templates#2]
Hi There

White screen of death was reported in the InvoiceNinja discord support channel.

Could you please expedite the update to 5.10 as the fix for us?

TIA

**Comment by SpitFireRSA** [comment]
Apologies, noted you don't maintain the image.

**Comment by kiwimato** [comment]
@SpitFireRSA actually I do maintain the image, but it's just built on top of the image that comes from InvoiceNinja so it works with UnRAID without adding nginx etc.

Just for future reference, you can find the image being built [here](https://github.com/kiwimato/invoiceninja-v5-unraid/actions) which is built every night, and my UnRAID is already running `v5.10.4-C160` without me doing anything as I have automatic updates for containers. In other words, just pulling the latest image should get you this version.
Do you need a newer version than this? I can force a build now if you need it.
![image](https://github.com/kiwimato/unraid-templates/assets/56123381/bc7a80af-b5fc-4a25-b6f2-d13dd3ec8da1)

**Comment by SpitFireRSA** [comment]
Thanks for confirming.  I did force in update via the Unraid GUI, but maybe it didn't actually go an pull the latest image. 

I am going to delete the image and try again.  Thanks!

**Comment by SpitFireRSA** [comment]
Hmm - even after stopping the container, removing the docker container, removing the docker image and applying the docker template with all my vars again, I am still on the same version.

<img width="383" alt="image" src="https://github.com/kiwimato/unraid-templates/assets/17448082/7d449e15-de14-49f7-b6f4-d5fcbed109e4">

<img width="722" alt="image" src="https://github.com/kiwimato/unraid-templates/assets/17448082/f34b7846-df93-41b7-9593-1ba9349be740">

Can you please force it?

**Comment by SpitFireRSA** [comment]
Note via Mobile App it says I am on the latest:

<img width="197" alt="image" src="https://github.com/kiwimato/unraid-templates/assets/17448082/858c8e70-4021-4713-8755-512f0986c7fb">

I did use another browser and cleared cache - so not sure where to from here.

**Comment by kiwimato** [comment]
wait, what? your browser says you're on v14.04? what version is that even? are you sure you're checking the same installation? Can you stop the container and try to access it? If it still works you're checking something else.

**Comment by SpitFireRSA** [comment]
100% it is the same installation.   I see the same companies, invoices etc.  Sign in is with the same URL.

**Comment by SpitFireRSA** [comment]
I know you can't see the server URL on the right, but I signed out and back in again double checking the FQDN

<img width="1173" alt="image" src="https://github.com/kiwimato/unraid-templates/assets/17448082/064d3f35-162a-408b-b144-8e08e6cb0364">

**Comment by SpitFireRSA** [comment]
I see the same version in Edge: 

<img width="894" alt="image" src="https://github.com/kiwimato/unraid-templates/assets/17448082/dc9b5da0-77c0-49ef-aca4-3d85ca6d886a">

**Comment by SpitFireRSA** [comment]
But worth adding that the issue does not happen in Edge.  So now for now things are fine, just weird why chrome would have this white screen issue.

**Comment by kiwimato** [comment]
in any case, it's a super weird issue, I just scheduled a new [build](https://github.com/kiwimato/invoiceninja-v5-unraid/actions/runs/9849775783)

where do you click that about button? I click it here:
![image](https://github.com/kiwimato/unraid-templates/assets/56123381/4cdd87a8-0c0b-41ca-8c48-b301636874d8)

**Comment by SpitFireRSA** [comment]
Yes, that's the one.  The circled "i" bottom left of the left hand pane.

**Comment by kiwimato** [comment]
Interesting, the v14 seems to be the ReactAPP version, which I don't know what this is, I see 2 issues mentioning v14:
https://github.com/invoiceninja/invoiceninja/issues/9672
https://github.com/invoiceninja/invoiceninja/issues/9659

**Comment by kiwimato** [comment]
I'm using Chrome on Linux btw, so maybe we get different things based on the OS/browser.

**Comment by kiwimato** [comment]
and the path you're using, `/clients` doesnt work for me, so I suspect our setup is a bit different
![image](https://github.com/kiwimato/unraid-templates/assets/56123381/e9fdaba3-0fb6-4f83-a650-827c5094dda0)

**Comment by kiwimato** [comment]
I think you have React enabled, and I don't, not sure if it's the default nowadays: https://forum.invoiceninja.com/t/enabling-react-results-in-a-blank-screen/12066

**Comment by SpitFireRSA** [comment]
Try `/client`

**Comment by SpitFireRSA** [comment]
I appreciate your help on this one -

**Comment by kiwimato** [comment]
yeah /client works but i never created a client user since I never needed this functionality.
